### ISSUE TITLE
Dummy issue for uploading images

### ISSUE THREAD

**Issue by shannah** [codenameone/codenameone-demos#1]
![image](https://cloud.githubusercontent.com/assets/2677562/13191694/5db26e12-d71a-11e5-8b21-3058e240910d.png)

![image](https://cloud.githubusercontent.com/assets/2677562/13191729/9108cf22-d71a-11e5-86d6-d5c752826596.png)

**Comment by codenameone** [comment]
The right way to do this is to write a small section in the Components section of the developer guide.

You can place sync with the developer guide
